services:
    express:
        image: node:20-bookworm-slim
        command: ["node", "/app/server.js"] 
        volumes:
          - ./expressServer:/app/
        ports:
          - 3000:3000
        env_file:
          ./.env

    postgres:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_DB=${DATABASE_NAME}
      env_file:
        - ./.env
      ports:
        - 5432:5432
      volumes:
        - ./postgres:/var/lib/postgresql/data
        - ./postgres:/backups/
